// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/masterNodeKnowerService/MasterNodeKnowerProtocol.proto

package masterNodeKnowerService;

public final class MasterNodeKnowerProtocol {
  private MasterNodeKnowerProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MasterNodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string clusterName = 1;
    boolean hasClusterName();
    String getClusterName();
    
    // required string masterIp = 2;
    boolean hasMasterIp();
    String getMasterIp();
    
    // required uint32 masterPort = 3;
    boolean hasMasterPort();
    int getMasterPort();
  }
  public static final class MasterNode extends
      com.google.protobuf.GeneratedMessage
      implements MasterNodeOrBuilder {
    // Use MasterNode.newBuilder() to construct.
    private MasterNode(Builder builder) {
      super(builder);
    }
    private MasterNode(boolean noInit) {}
    
    private static final MasterNode defaultInstance;
    public static MasterNode getDefaultInstance() {
      return defaultInstance;
    }
    
    public MasterNode getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return masterNodeKnowerService.MasterNodeKnowerProtocol.internal_static_masterNodeKnowerService_MasterNode_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return masterNodeKnowerService.MasterNodeKnowerProtocol.internal_static_masterNodeKnowerService_MasterNode_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string clusterName = 1;
    public static final int CLUSTERNAME_FIELD_NUMBER = 1;
    private java.lang.Object clusterName_;
    public boolean hasClusterName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getClusterName() {
      java.lang.Object ref = clusterName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          clusterName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClusterNameBytes() {
      java.lang.Object ref = clusterName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        clusterName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string masterIp = 2;
    public static final int MASTERIP_FIELD_NUMBER = 2;
    private java.lang.Object masterIp_;
    public boolean hasMasterIp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMasterIp() {
      java.lang.Object ref = masterIp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          masterIp_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMasterIpBytes() {
      java.lang.Object ref = masterIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        masterIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required uint32 masterPort = 3;
    public static final int MASTERPORT_FIELD_NUMBER = 3;
    private int masterPort_;
    public boolean hasMasterPort() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getMasterPort() {
      return masterPort_;
    }
    
    private void initFields() {
      clusterName_ = "";
      masterIp_ = "";
      masterPort_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasClusterName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMasterIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMasterPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getClusterNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMasterIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, masterPort_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getClusterNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMasterIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, masterPort_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return masterNodeKnowerService.MasterNodeKnowerProtocol.internal_static_masterNodeKnowerService_MasterNode_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return masterNodeKnowerService.MasterNodeKnowerProtocol.internal_static_masterNodeKnowerService_MasterNode_fieldAccessorTable;
      }
      
      // Construct using masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        clusterName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        masterIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        masterPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.getDescriptor();
      }
      
      public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode getDefaultInstanceForType() {
        return masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.getDefaultInstance();
      }
      
      public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode build() {
        masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode buildPartial() {
        masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode result = new masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clusterName_ = clusterName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.masterIp_ = masterIp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.masterPort_ = masterPort_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode) {
          return mergeFrom((masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode other) {
        if (other == masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.getDefaultInstance()) return this;
        if (other.hasClusterName()) {
          setClusterName(other.getClusterName());
        }
        if (other.hasMasterIp()) {
          setMasterIp(other.getMasterIp());
        }
        if (other.hasMasterPort()) {
          setMasterPort(other.getMasterPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasClusterName()) {
          
          return false;
        }
        if (!hasMasterIp()) {
          
          return false;
        }
        if (!hasMasterPort()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              clusterName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              masterIp_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              masterPort_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string clusterName = 1;
      private java.lang.Object clusterName_ = "";
      public boolean hasClusterName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getClusterName() {
        java.lang.Object ref = clusterName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          clusterName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setClusterName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clusterName_ = value;
        onChanged();
        return this;
      }
      public Builder clearClusterName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clusterName_ = getDefaultInstance().getClusterName();
        onChanged();
        return this;
      }
      void setClusterName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        clusterName_ = value;
        onChanged();
      }
      
      // required string masterIp = 2;
      private java.lang.Object masterIp_ = "";
      public boolean hasMasterIp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMasterIp() {
        java.lang.Object ref = masterIp_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          masterIp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMasterIp(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        masterIp_ = value;
        onChanged();
        return this;
      }
      public Builder clearMasterIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        masterIp_ = getDefaultInstance().getMasterIp();
        onChanged();
        return this;
      }
      void setMasterIp(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        masterIp_ = value;
        onChanged();
      }
      
      // required uint32 masterPort = 3;
      private int masterPort_ ;
      public boolean hasMasterPort() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getMasterPort() {
        return masterPort_;
      }
      public Builder setMasterPort(int value) {
        bitField0_ |= 0x00000004;
        masterPort_ = value;
        onChanged();
        return this;
      }
      public Builder clearMasterPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        masterPort_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:masterNodeKnowerService.MasterNode)
    }
    
    static {
      defaultInstance = new MasterNode(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:masterNodeKnowerService.MasterNode)
  }
  
  public interface DNSRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .masterNodeKnowerService.DNSRequest.Action action = 1;
    boolean hasAction();
    masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.Action getAction();
    
    // optional string clusterName = 2;
    boolean hasClusterName();
    String getClusterName();
    
    // optional .masterNodeKnowerService.MasterNode masterNode = 3;
    boolean hasMasterNode();
    masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode getMasterNode();
    masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder getMasterNodeOrBuilder();
  }
  public static final class DNSRequest extends
      com.google.protobuf.GeneratedMessage
      implements DNSRequestOrBuilder {
    // Use DNSRequest.newBuilder() to construct.
    private DNSRequest(Builder builder) {
      super(builder);
    }
    private DNSRequest(boolean noInit) {}
    
    private static final DNSRequest defaultInstance;
    public static DNSRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public DNSRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return masterNodeKnowerService.MasterNodeKnowerProtocol.internal_static_masterNodeKnowerService_DNSRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return masterNodeKnowerService.MasterNodeKnowerProtocol.internal_static_masterNodeKnowerService_DNSRequest_fieldAccessorTable;
    }
    
    public enum Action
        implements com.google.protobuf.ProtocolMessageEnum {
      GET(0, 0),
      PUT(1, 1),
      ;
      
      public static final int GET_VALUE = 0;
      public static final int PUT_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Action valueOf(int value) {
        switch (value) {
          case 0: return GET;
          case 1: return PUT;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Action>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Action>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Action>() {
              public Action findValueByNumber(int number) {
                return Action.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Action[] VALUES = {
        GET, PUT, 
      };
      
      public static Action valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Action(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:masterNodeKnowerService.DNSRequest.Action)
    }
    
    private int bitField0_;
    // required .masterNodeKnowerService.DNSRequest.Action action = 1;
    public static final int ACTION_FIELD_NUMBER = 1;
    private masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.Action action_;
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.Action getAction() {
      return action_;
    }
    
    // optional string clusterName = 2;
    public static final int CLUSTERNAME_FIELD_NUMBER = 2;
    private java.lang.Object clusterName_;
    public boolean hasClusterName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getClusterName() {
      java.lang.Object ref = clusterName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          clusterName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClusterNameBytes() {
      java.lang.Object ref = clusterName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        clusterName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .masterNodeKnowerService.MasterNode masterNode = 3;
    public static final int MASTERNODE_FIELD_NUMBER = 3;
    private masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode masterNode_;
    public boolean hasMasterNode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode getMasterNode() {
      return masterNode_;
    }
    public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder getMasterNodeOrBuilder() {
      return masterNode_;
    }
    
    private void initFields() {
      action_ = masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.Action.GET;
      clusterName_ = "";
      masterNode_ = masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasMasterNode()) {
        if (!getMasterNode().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getClusterNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, masterNode_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClusterNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, masterNode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return masterNodeKnowerService.MasterNodeKnowerProtocol.internal_static_masterNodeKnowerService_DNSRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return masterNodeKnowerService.MasterNodeKnowerProtocol.internal_static_masterNodeKnowerService_DNSRequest_fieldAccessorTable;
      }
      
      // Construct using masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMasterNodeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        action_ = masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.Action.GET;
        bitField0_ = (bitField0_ & ~0x00000001);
        clusterName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (masterNodeBuilder_ == null) {
          masterNode_ = masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.getDefaultInstance();
        } else {
          masterNodeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.getDescriptor();
      }
      
      public masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest getDefaultInstanceForType() {
        return masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.getDefaultInstance();
      }
      
      public masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest build() {
        masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest buildPartial() {
        masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest result = new masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clusterName_ = clusterName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (masterNodeBuilder_ == null) {
          result.masterNode_ = masterNode_;
        } else {
          result.masterNode_ = masterNodeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest) {
          return mergeFrom((masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest other) {
        if (other == masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.getDefaultInstance()) return this;
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasClusterName()) {
          setClusterName(other.getClusterName());
        }
        if (other.hasMasterNode()) {
          mergeMasterNode(other.getMasterNode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAction()) {
          
          return false;
        }
        if (hasMasterNode()) {
          if (!getMasterNode().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.Action value = masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.Action.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                action_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              clusterName_ = input.readBytes();
              break;
            }
            case 26: {
              masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder subBuilder = masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.newBuilder();
              if (hasMasterNode()) {
                subBuilder.mergeFrom(getMasterNode());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMasterNode(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .masterNodeKnowerService.DNSRequest.Action action = 1;
      private masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.Action action_ = masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.Action.GET;
      public boolean hasAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.Action getAction() {
        return action_;
      }
      public Builder setAction(masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.Action value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        action_ = value;
        onChanged();
        return this;
      }
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.Action.GET;
        onChanged();
        return this;
      }
      
      // optional string clusterName = 2;
      private java.lang.Object clusterName_ = "";
      public boolean hasClusterName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getClusterName() {
        java.lang.Object ref = clusterName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          clusterName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setClusterName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clusterName_ = value;
        onChanged();
        return this;
      }
      public Builder clearClusterName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clusterName_ = getDefaultInstance().getClusterName();
        onChanged();
        return this;
      }
      void setClusterName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        clusterName_ = value;
        onChanged();
      }
      
      // optional .masterNodeKnowerService.MasterNode masterNode = 3;
      private masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode masterNode_ = masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder> masterNodeBuilder_;
      public boolean hasMasterNode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode getMasterNode() {
        if (masterNodeBuilder_ == null) {
          return masterNode_;
        } else {
          return masterNodeBuilder_.getMessage();
        }
      }
      public Builder setMasterNode(masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode value) {
        if (masterNodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          masterNode_ = value;
          onChanged();
        } else {
          masterNodeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setMasterNode(
          masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder builderForValue) {
        if (masterNodeBuilder_ == null) {
          masterNode_ = builderForValue.build();
          onChanged();
        } else {
          masterNodeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeMasterNode(masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode value) {
        if (masterNodeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              masterNode_ != masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.getDefaultInstance()) {
            masterNode_ =
              masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.newBuilder(masterNode_).mergeFrom(value).buildPartial();
          } else {
            masterNode_ = value;
          }
          onChanged();
        } else {
          masterNodeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearMasterNode() {
        if (masterNodeBuilder_ == null) {
          masterNode_ = masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.getDefaultInstance();
          onChanged();
        } else {
          masterNodeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder getMasterNodeBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getMasterNodeFieldBuilder().getBuilder();
      }
      public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder getMasterNodeOrBuilder() {
        if (masterNodeBuilder_ != null) {
          return masterNodeBuilder_.getMessageOrBuilder();
        } else {
          return masterNode_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder> 
          getMasterNodeFieldBuilder() {
        if (masterNodeBuilder_ == null) {
          masterNodeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder>(
                  masterNode_,
                  getParentForChildren(),
                  isClean());
          masterNode_ = null;
        }
        return masterNodeBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:masterNodeKnowerService.DNSRequest)
    }
    
    static {
      defaultInstance = new DNSRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:masterNodeKnowerService.DNSRequest)
  }
  
  public interface DNSResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .masterNodeKnowerService.DNSResponse.Status status = 1;
    boolean hasStatus();
    masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.Status getStatus();
    
    // optional string errorMessage = 2;
    boolean hasErrorMessage();
    String getErrorMessage();
    
    // repeated .masterNodeKnowerService.MasterNode masterNode = 3;
    java.util.List<masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode> 
        getMasterNodeList();
    masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode getMasterNode(int index);
    int getMasterNodeCount();
    java.util.List<? extends masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder> 
        getMasterNodeOrBuilderList();
    masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder getMasterNodeOrBuilder(
        int index);
  }
  public static final class DNSResponse extends
      com.google.protobuf.GeneratedMessage
      implements DNSResponseOrBuilder {
    // Use DNSResponse.newBuilder() to construct.
    private DNSResponse(Builder builder) {
      super(builder);
    }
    private DNSResponse(boolean noInit) {}
    
    private static final DNSResponse defaultInstance;
    public static DNSResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public DNSResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return masterNodeKnowerService.MasterNodeKnowerProtocol.internal_static_masterNodeKnowerService_DNSResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return masterNodeKnowerService.MasterNodeKnowerProtocol.internal_static_masterNodeKnowerService_DNSResponse_fieldAccessorTable;
    }
    
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      OK(0, 0),
      ERROR(1, 1),
      ;
      
      public static final int OK_VALUE = 0;
      public static final int ERROR_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Status valueOf(int value) {
        switch (value) {
          case 0: return OK;
          case 1: return ERROR;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Status[] VALUES = {
        OK, ERROR, 
      };
      
      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Status(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:masterNodeKnowerService.DNSResponse.Status)
    }
    
    private int bitField0_;
    // required .masterNodeKnowerService.DNSResponse.Status status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.Status status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.Status getStatus() {
      return status_;
    }
    
    // optional string errorMessage = 2;
    public static final int ERRORMESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object errorMessage_;
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .masterNodeKnowerService.MasterNode masterNode = 3;
    public static final int MASTERNODE_FIELD_NUMBER = 3;
    private java.util.List<masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode> masterNode_;
    public java.util.List<masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode> getMasterNodeList() {
      return masterNode_;
    }
    public java.util.List<? extends masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder> 
        getMasterNodeOrBuilderList() {
      return masterNode_;
    }
    public int getMasterNodeCount() {
      return masterNode_.size();
    }
    public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode getMasterNode(int index) {
      return masterNode_.get(index);
    }
    public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder getMasterNodeOrBuilder(
        int index) {
      return masterNode_.get(index);
    }
    
    private void initFields() {
      status_ = masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.Status.OK;
      errorMessage_ = "";
      masterNode_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMasterNodeCount(); i++) {
        if (!getMasterNode(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, status_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrorMessageBytes());
      }
      for (int i = 0; i < masterNode_.size(); i++) {
        output.writeMessage(3, masterNode_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrorMessageBytes());
      }
      for (int i = 0; i < masterNode_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, masterNode_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return masterNodeKnowerService.MasterNodeKnowerProtocol.internal_static_masterNodeKnowerService_DNSResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return masterNodeKnowerService.MasterNodeKnowerProtocol.internal_static_masterNodeKnowerService_DNSResponse_fieldAccessorTable;
      }
      
      // Construct using masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMasterNodeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        status_ = masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.Status.OK;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (masterNodeBuilder_ == null) {
          masterNode_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          masterNodeBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.getDescriptor();
      }
      
      public masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse getDefaultInstanceForType() {
        return masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.getDefaultInstance();
      }
      
      public masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse build() {
        masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse buildPartial() {
        masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse result = new masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorMessage_ = errorMessage_;
        if (masterNodeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            masterNode_ = java.util.Collections.unmodifiableList(masterNode_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.masterNode_ = masterNode_;
        } else {
          result.masterNode_ = masterNodeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse) {
          return mergeFrom((masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse other) {
        if (other == masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasErrorMessage()) {
          setErrorMessage(other.getErrorMessage());
        }
        if (masterNodeBuilder_ == null) {
          if (!other.masterNode_.isEmpty()) {
            if (masterNode_.isEmpty()) {
              masterNode_ = other.masterNode_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMasterNodeIsMutable();
              masterNode_.addAll(other.masterNode_);
            }
            onChanged();
          }
        } else {
          if (!other.masterNode_.isEmpty()) {
            if (masterNodeBuilder_.isEmpty()) {
              masterNodeBuilder_.dispose();
              masterNodeBuilder_ = null;
              masterNode_ = other.masterNode_;
              bitField0_ = (bitField0_ & ~0x00000004);
              masterNodeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMasterNodeFieldBuilder() : null;
            } else {
              masterNodeBuilder_.addAllMessages(other.masterNode_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        for (int i = 0; i < getMasterNodeCount(); i++) {
          if (!getMasterNode(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.Status value = masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.Status.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                status_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              errorMessage_ = input.readBytes();
              break;
            }
            case 26: {
              masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder subBuilder = masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMasterNode(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .masterNodeKnowerService.DNSResponse.Status status = 1;
      private masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.Status status_ = masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.Status.OK;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.Status getStatus() {
        return status_;
      }
      public Builder setStatus(masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.Status.OK;
        onChanged();
        return this;
      }
      
      // optional string errorMessage = 2;
      private java.lang.Object errorMessage_ = "";
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          errorMessage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setErrorMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      void setErrorMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        errorMessage_ = value;
        onChanged();
      }
      
      // repeated .masterNodeKnowerService.MasterNode masterNode = 3;
      private java.util.List<masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode> masterNode_ =
        java.util.Collections.emptyList();
      private void ensureMasterNodeIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          masterNode_ = new java.util.ArrayList<masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode>(masterNode_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder> masterNodeBuilder_;
      
      public java.util.List<masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode> getMasterNodeList() {
        if (masterNodeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(masterNode_);
        } else {
          return masterNodeBuilder_.getMessageList();
        }
      }
      public int getMasterNodeCount() {
        if (masterNodeBuilder_ == null) {
          return masterNode_.size();
        } else {
          return masterNodeBuilder_.getCount();
        }
      }
      public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode getMasterNode(int index) {
        if (masterNodeBuilder_ == null) {
          return masterNode_.get(index);
        } else {
          return masterNodeBuilder_.getMessage(index);
        }
      }
      public Builder setMasterNode(
          int index, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode value) {
        if (masterNodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMasterNodeIsMutable();
          masterNode_.set(index, value);
          onChanged();
        } else {
          masterNodeBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMasterNode(
          int index, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder builderForValue) {
        if (masterNodeBuilder_ == null) {
          ensureMasterNodeIsMutable();
          masterNode_.set(index, builderForValue.build());
          onChanged();
        } else {
          masterNodeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMasterNode(masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode value) {
        if (masterNodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMasterNodeIsMutable();
          masterNode_.add(value);
          onChanged();
        } else {
          masterNodeBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMasterNode(
          int index, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode value) {
        if (masterNodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMasterNodeIsMutable();
          masterNode_.add(index, value);
          onChanged();
        } else {
          masterNodeBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMasterNode(
          masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder builderForValue) {
        if (masterNodeBuilder_ == null) {
          ensureMasterNodeIsMutable();
          masterNode_.add(builderForValue.build());
          onChanged();
        } else {
          masterNodeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMasterNode(
          int index, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder builderForValue) {
        if (masterNodeBuilder_ == null) {
          ensureMasterNodeIsMutable();
          masterNode_.add(index, builderForValue.build());
          onChanged();
        } else {
          masterNodeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMasterNode(
          java.lang.Iterable<? extends masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode> values) {
        if (masterNodeBuilder_ == null) {
          ensureMasterNodeIsMutable();
          super.addAll(values, masterNode_);
          onChanged();
        } else {
          masterNodeBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMasterNode() {
        if (masterNodeBuilder_ == null) {
          masterNode_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          masterNodeBuilder_.clear();
        }
        return this;
      }
      public Builder removeMasterNode(int index) {
        if (masterNodeBuilder_ == null) {
          ensureMasterNodeIsMutable();
          masterNode_.remove(index);
          onChanged();
        } else {
          masterNodeBuilder_.remove(index);
        }
        return this;
      }
      public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder getMasterNodeBuilder(
          int index) {
        return getMasterNodeFieldBuilder().getBuilder(index);
      }
      public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder getMasterNodeOrBuilder(
          int index) {
        if (masterNodeBuilder_ == null) {
          return masterNode_.get(index);  } else {
          return masterNodeBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder> 
           getMasterNodeOrBuilderList() {
        if (masterNodeBuilder_ != null) {
          return masterNodeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(masterNode_);
        }
      }
      public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder addMasterNodeBuilder() {
        return getMasterNodeFieldBuilder().addBuilder(
            masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.getDefaultInstance());
      }
      public masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder addMasterNodeBuilder(
          int index) {
        return getMasterNodeFieldBuilder().addBuilder(
            index, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.getDefaultInstance());
      }
      public java.util.List<masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder> 
           getMasterNodeBuilderList() {
        return getMasterNodeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder> 
          getMasterNodeFieldBuilder() {
        if (masterNodeBuilder_ == null) {
          masterNodeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder, masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNodeOrBuilder>(
                  masterNode_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          masterNode_ = null;
        }
        return masterNodeBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:masterNodeKnowerService.DNSResponse)
    }
    
    static {
      defaultInstance = new DNSResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:masterNodeKnowerService.DNSResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_masterNodeKnowerService_MasterNode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_masterNodeKnowerService_MasterNode_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_masterNodeKnowerService_DNSRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_masterNodeKnowerService_DNSRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_masterNodeKnowerService_DNSResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_masterNodeKnowerService_DNSResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:src/masterNodeKnowerService/MasterNode" +
      "KnowerProtocol.proto\022\027masterNodeKnowerSe" +
      "rvice\"G\n\nMasterNode\022\023\n\013clusterName\030\001 \002(\t" +
      "\022\020\n\010masterIp\030\002 \002(\t\022\022\n\nmasterPort\030\003 \002(\r\"\262" +
      "\001\n\nDNSRequest\022:\n\006action\030\001 \002(\0162*.masterNo" +
      "deKnowerService.DNSRequest.Action\022\023\n\013clu" +
      "sterName\030\002 \001(\t\0227\n\nmasterNode\030\003 \001(\0132#.mas" +
      "terNodeKnowerService.MasterNode\"\032\n\006Actio" +
      "n\022\007\n\003GET\020\000\022\007\n\003PUT\020\001\"\266\001\n\013DNSResponse\022;\n\006s" +
      "tatus\030\001 \002(\0162+.masterNodeKnowerService.DN",
      "SResponse.Status\022\024\n\014errorMessage\030\002 \001(\t\0227" +
      "\n\nmasterNode\030\003 \003(\0132#.masterNodeKnowerSer" +
      "vice.MasterNode\"\033\n\006Status\022\006\n\002OK\020\000\022\t\n\005ERR" +
      "OR\020\001B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_masterNodeKnowerService_MasterNode_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_masterNodeKnowerService_MasterNode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_masterNodeKnowerService_MasterNode_descriptor,
              new java.lang.String[] { "ClusterName", "MasterIp", "MasterPort", },
              masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.class,
              masterNodeKnowerService.MasterNodeKnowerProtocol.MasterNode.Builder.class);
          internal_static_masterNodeKnowerService_DNSRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_masterNodeKnowerService_DNSRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_masterNodeKnowerService_DNSRequest_descriptor,
              new java.lang.String[] { "Action", "ClusterName", "MasterNode", },
              masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.class,
              masterNodeKnowerService.MasterNodeKnowerProtocol.DNSRequest.Builder.class);
          internal_static_masterNodeKnowerService_DNSResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_masterNodeKnowerService_DNSResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_masterNodeKnowerService_DNSResponse_descriptor,
              new java.lang.String[] { "Status", "ErrorMessage", "MasterNode", },
              masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.class,
              masterNodeKnowerService.MasterNodeKnowerProtocol.DNSResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
