// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Photo.proto

package some.package.275;

public final class SomeClass {
  private SomeClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PhotoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:some.photo.package.PhotoResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .some.photo.package.PhotoResponse.ResponseFlag responseFlag = 1 [default = success];</code>
     */
    boolean hasResponseFlag();
    /**
     * <code>required .some.photo.package.PhotoResponse.ResponseFlag responseFlag = 1 [default = success];</code>
     */
    some.package.275.SomeClass.PhotoResponse.ResponseFlag getResponseFlag();

    /**
     * <code>required .some.photo.package.PhotoResponse.ResponseType responseType = 2 [default = read];</code>
     */
    boolean hasResponseType();
    /**
     * <code>required .some.photo.package.PhotoResponse.ResponseType responseType = 2 [default = read];</code>
     */
    some.package.275.SomeClass.PhotoResponse.ResponseType getResponseType();

    /**
     * <code>optional int64 lastModified = 3;</code>
     *
     * <pre>
     * Unix timestamp
     * </pre>
     */
    boolean hasLastModified();
    /**
     * <code>optional int64 lastModified = 3;</code>
     *
     * <pre>
     * Unix timestamp
     * </pre>
     */
    long getLastModified();

    /**
     * <code>optional string uuid = 4;</code>
     *
     * <pre>
     * Required for all types, optional for simplicity/flexibility
     * </pre>
     */
    boolean hasUuid();
    /**
     * <code>optional string uuid = 4;</code>
     *
     * <pre>
     * Required for all types, optional for simplicity/flexibility
     * </pre>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 4;</code>
     *
     * <pre>
     * Required for all types, optional for simplicity/flexibility
     * </pre>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional bytes photo = 5;</code>
     *
     * <pre>
     * Required for Type 0
     * </pre>
     */
    boolean hasPhoto();
    /**
     * <code>optional bytes photo = 5;</code>
     *
     * <pre>
     * Required for Type 0
     * </pre>
     */
    com.google.protobuf.ByteString getPhoto();
  }
  /**
   * Protobuf type {@code some.photo.package.PhotoResponse}
   */
  public static final class PhotoResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:some.photo.package.PhotoResponse)
      PhotoResponseOrBuilder {
    // Use PhotoResponse.newBuilder() to construct.
    private PhotoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PhotoResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PhotoResponse defaultInstance;
    public static PhotoResponse getDefaultInstance() {
      return defaultInstance;
    }

    public PhotoResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PhotoResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              some.package.275.SomeClass.PhotoResponse.ResponseFlag value = some.package.275.SomeClass.PhotoResponse.ResponseFlag.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                responseFlag_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              some.package.275.SomeClass.PhotoResponse.ResponseType value = some.package.275.SomeClass.PhotoResponse.ResponseType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                responseType_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              lastModified_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              uuid_ = bs;
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              photo_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return some.package.275.SomeClass.internal_static_some_photo_package_PhotoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return some.package.275.SomeClass.internal_static_some_photo_package_PhotoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              some.package.275.SomeClass.PhotoResponse.class, some.package.275.SomeClass.PhotoResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<PhotoResponse> PARSER =
        new com.google.protobuf.AbstractParser<PhotoResponse>() {
      public PhotoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhotoResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PhotoResponse> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code some.photo.package.PhotoResponse.ResponseFlag}
     */
    public enum ResponseFlag
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>success = 0;</code>
       */
      success(0, 0),
      /**
       * <code>failure = 1;</code>
       */
      failure(1, 1),
      ;

      /**
       * <code>success = 0;</code>
       */
      public static final int success_VALUE = 0;
      /**
       * <code>failure = 1;</code>
       */
      public static final int failure_VALUE = 1;


      public final int getNumber() { return value; }

      public static ResponseFlag valueOf(int value) {
        switch (value) {
          case 0: return success;
          case 1: return failure;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResponseFlag>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResponseFlag>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResponseFlag>() {
              public ResponseFlag findValueByNumber(int number) {
                return ResponseFlag.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return some.package.275.SomeClass.PhotoResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResponseFlag[] VALUES = values();

      public static ResponseFlag valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResponseFlag(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:some.photo.package.PhotoResponse.ResponseFlag)
    }

    /**
     * Protobuf enum {@code some.photo.package.PhotoResponse.ResponseType}
     */
    public enum ResponseType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>read = 0;</code>
       */
      read(0, 0),
      /**
       * <code>write = 1;</code>
       */
      write(1, 1),
      /**
       * <code>delete = 2;</code>
       */
      delete(2, 2),
      ;

      /**
       * <code>read = 0;</code>
       */
      public static final int read_VALUE = 0;
      /**
       * <code>write = 1;</code>
       */
      public static final int write_VALUE = 1;
      /**
       * <code>delete = 2;</code>
       */
      public static final int delete_VALUE = 2;


      public final int getNumber() { return value; }

      public static ResponseType valueOf(int value) {
        switch (value) {
          case 0: return read;
          case 1: return write;
          case 2: return delete;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
              public ResponseType findValueByNumber(int number) {
                return ResponseType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return some.package.275.SomeClass.PhotoResponse.getDescriptor().getEnumTypes().get(1);
      }

      private static final ResponseType[] VALUES = values();

      public static ResponseType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResponseType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:some.photo.package.PhotoResponse.ResponseType)
    }

    private int bitField0_;
    public static final int RESPONSEFLAG_FIELD_NUMBER = 1;
    private some.package.275.SomeClass.PhotoResponse.ResponseFlag responseFlag_;
    /**
     * <code>required .some.photo.package.PhotoResponse.ResponseFlag responseFlag = 1 [default = success];</code>
     */
    public boolean hasResponseFlag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .some.photo.package.PhotoResponse.ResponseFlag responseFlag = 1 [default = success];</code>
     */
    public some.package.275.SomeClass.PhotoResponse.ResponseFlag getResponseFlag() {
      return responseFlag_;
    }

    public static final int RESPONSETYPE_FIELD_NUMBER = 2;
    private some.package.275.SomeClass.PhotoResponse.ResponseType responseType_;
    /**
     * <code>required .some.photo.package.PhotoResponse.ResponseType responseType = 2 [default = read];</code>
     */
    public boolean hasResponseType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .some.photo.package.PhotoResponse.ResponseType responseType = 2 [default = read];</code>
     */
    public some.package.275.SomeClass.PhotoResponse.ResponseType getResponseType() {
      return responseType_;
    }

    public static final int LASTMODIFIED_FIELD_NUMBER = 3;
    private long lastModified_;
    /**
     * <code>optional int64 lastModified = 3;</code>
     *
     * <pre>
     * Unix timestamp
     * </pre>
     */
    public boolean hasLastModified() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 lastModified = 3;</code>
     *
     * <pre>
     * Unix timestamp
     * </pre>
     */
    public long getLastModified() {
      return lastModified_;
    }

    public static final int UUID_FIELD_NUMBER = 4;
    private java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 4;</code>
     *
     * <pre>
     * Required for all types, optional for simplicity/flexibility
     * </pre>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string uuid = 4;</code>
     *
     * <pre>
     * Required for all types, optional for simplicity/flexibility
     * </pre>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 4;</code>
     *
     * <pre>
     * Required for all types, optional for simplicity/flexibility
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHOTO_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString photo_;
    /**
     * <code>optional bytes photo = 5;</code>
     *
     * <pre>
     * Required for Type 0
     * </pre>
     */
    public boolean hasPhoto() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes photo = 5;</code>
     *
     * <pre>
     * Required for Type 0
     * </pre>
     */
    public com.google.protobuf.ByteString getPhoto() {
      return photo_;
    }

    private void initFields() {
      responseFlag_ = some.package.275.SomeClass.PhotoResponse.ResponseFlag.success;
      responseType_ = some.package.275.SomeClass.PhotoResponse.ResponseType.read;
      lastModified_ = 0L;
      uuid_ = "";
      photo_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResponseFlag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResponseType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, responseFlag_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, responseType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, lastModified_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUuidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, photo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, responseFlag_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, responseType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, lastModified_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUuidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, photo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static some.package.275.SomeClass.PhotoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static some.package.275.SomeClass.PhotoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static some.package.275.SomeClass.PhotoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static some.package.275.SomeClass.PhotoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static some.package.275.SomeClass.PhotoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static some.package.275.SomeClass.PhotoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static some.package.275.SomeClass.PhotoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static some.package.275.SomeClass.PhotoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static some.package.275.SomeClass.PhotoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static some.package.275.SomeClass.PhotoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(some.package.275.SomeClass.PhotoResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code some.photo.package.PhotoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:some.photo.package.PhotoResponse)
        some.package.275.SomeClass.PhotoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return some.package.275.SomeClass.internal_static_some_photo_package_PhotoResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return some.package.275.SomeClass.internal_static_some_photo_package_PhotoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                some.package.275.SomeClass.PhotoResponse.class, some.package.275.SomeClass.PhotoResponse.Builder.class);
      }

      // Construct using some.package.275.SomeClass.PhotoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        responseFlag_ = some.package.275.SomeClass.PhotoResponse.ResponseFlag.success;
        bitField0_ = (bitField0_ & ~0x00000001);
        responseType_ = some.package.275.SomeClass.PhotoResponse.ResponseType.read;
        bitField0_ = (bitField0_ & ~0x00000002);
        lastModified_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        photo_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return some.package.275.SomeClass.internal_static_some_photo_package_PhotoResponse_descriptor;
      }

      public some.package.275.SomeClass.PhotoResponse getDefaultInstanceForType() {
        return some.package.275.SomeClass.PhotoResponse.getDefaultInstance();
      }

      public some.package.275.SomeClass.PhotoResponse build() {
        some.package.275.SomeClass.PhotoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public some.package.275.SomeClass.PhotoResponse buildPartial() {
        some.package.275.SomeClass.PhotoResponse result = new some.package.275.SomeClass.PhotoResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.responseFlag_ = responseFlag_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.responseType_ = responseType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lastModified_ = lastModified_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.photo_ = photo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof some.package.275.SomeClass.PhotoResponse) {
          return mergeFrom((some.package.275.SomeClass.PhotoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(some.package.275.SomeClass.PhotoResponse other) {
        if (other == some.package.275.SomeClass.PhotoResponse.getDefaultInstance()) return this;
        if (other.hasResponseFlag()) {
          setResponseFlag(other.getResponseFlag());
        }
        if (other.hasResponseType()) {
          setResponseType(other.getResponseType());
        }
        if (other.hasLastModified()) {
          setLastModified(other.getLastModified());
        }
        if (other.hasUuid()) {
          bitField0_ |= 0x00000008;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasPhoto()) {
          setPhoto(other.getPhoto());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResponseFlag()) {
          
          return false;
        }
        if (!hasResponseType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        some.package.275.SomeClass.PhotoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (some.package.275.SomeClass.PhotoResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private some.package.275.SomeClass.PhotoResponse.ResponseFlag responseFlag_ = some.package.275.SomeClass.PhotoResponse.ResponseFlag.success;
      /**
       * <code>required .some.photo.package.PhotoResponse.ResponseFlag responseFlag = 1 [default = success];</code>
       */
      public boolean hasResponseFlag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .some.photo.package.PhotoResponse.ResponseFlag responseFlag = 1 [default = success];</code>
       */
      public some.package.275.SomeClass.PhotoResponse.ResponseFlag getResponseFlag() {
        return responseFlag_;
      }
      /**
       * <code>required .some.photo.package.PhotoResponse.ResponseFlag responseFlag = 1 [default = success];</code>
       */
      public Builder setResponseFlag(some.package.275.SomeClass.PhotoResponse.ResponseFlag value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        responseFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .some.photo.package.PhotoResponse.ResponseFlag responseFlag = 1 [default = success];</code>
       */
      public Builder clearResponseFlag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        responseFlag_ = some.package.275.SomeClass.PhotoResponse.ResponseFlag.success;
        onChanged();
        return this;
      }

      private some.package.275.SomeClass.PhotoResponse.ResponseType responseType_ = some.package.275.SomeClass.PhotoResponse.ResponseType.read;
      /**
       * <code>required .some.photo.package.PhotoResponse.ResponseType responseType = 2 [default = read];</code>
       */
      public boolean hasResponseType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .some.photo.package.PhotoResponse.ResponseType responseType = 2 [default = read];</code>
       */
      public some.package.275.SomeClass.PhotoResponse.ResponseType getResponseType() {
        return responseType_;
      }
      /**
       * <code>required .some.photo.package.PhotoResponse.ResponseType responseType = 2 [default = read];</code>
       */
      public Builder setResponseType(some.package.275.SomeClass.PhotoResponse.ResponseType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        responseType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .some.photo.package.PhotoResponse.ResponseType responseType = 2 [default = read];</code>
       */
      public Builder clearResponseType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        responseType_ = some.package.275.SomeClass.PhotoResponse.ResponseType.read;
        onChanged();
        return this;
      }

      private long lastModified_ ;
      /**
       * <code>optional int64 lastModified = 3;</code>
       *
       * <pre>
       * Unix timestamp
       * </pre>
       */
      public boolean hasLastModified() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 lastModified = 3;</code>
       *
       * <pre>
       * Unix timestamp
       * </pre>
       */
      public long getLastModified() {
        return lastModified_;
      }
      /**
       * <code>optional int64 lastModified = 3;</code>
       *
       * <pre>
       * Unix timestamp
       * </pre>
       */
      public Builder setLastModified(long value) {
        bitField0_ |= 0x00000004;
        lastModified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 lastModified = 3;</code>
       *
       * <pre>
       * Unix timestamp
       * </pre>
       */
      public Builder clearLastModified() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastModified_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 4;</code>
       *
       * <pre>
       * Required for all types, optional for simplicity/flexibility
       * </pre>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string uuid = 4;</code>
       *
       * <pre>
       * Required for all types, optional for simplicity/flexibility
       * </pre>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 4;</code>
       *
       * <pre>
       * Required for all types, optional for simplicity/flexibility
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 4;</code>
       *
       * <pre>
       * Required for all types, optional for simplicity/flexibility
       * </pre>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 4;</code>
       *
       * <pre>
       * Required for all types, optional for simplicity/flexibility
       * </pre>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 4;</code>
       *
       * <pre>
       * Required for all types, optional for simplicity/flexibility
       * </pre>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        uuid_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString photo_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes photo = 5;</code>
       *
       * <pre>
       * Required for Type 0
       * </pre>
       */
      public boolean hasPhoto() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes photo = 5;</code>
       *
       * <pre>
       * Required for Type 0
       * </pre>
       */
      public com.google.protobuf.ByteString getPhoto() {
        return photo_;
      }
      /**
       * <code>optional bytes photo = 5;</code>
       *
       * <pre>
       * Required for Type 0
       * </pre>
       */
      public Builder setPhoto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        photo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes photo = 5;</code>
       *
       * <pre>
       * Required for Type 0
       * </pre>
       */
      public Builder clearPhoto() {
        bitField0_ = (bitField0_ & ~0x00000010);
        photo_ = getDefaultInstance().getPhoto();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:some.photo.package.PhotoResponse)
    }

    static {
      defaultInstance = new PhotoResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:some.photo.package.PhotoResponse)
  }

  public interface PhotoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:some.photo.package.PhotoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .some.photo.package.PhotoRequest.RequestType requestType = 1 [default = read];</code>
     */
    boolean hasRequestType();
    /**
     * <code>required .some.photo.package.PhotoRequest.RequestType requestType = 1 [default = read];</code>
     */
    some.package.275.SomeClass.PhotoRequest.RequestType getRequestType();

    /**
     * <code>optional string uuid = 2;</code>
     *
     * <pre>
     * Required for types 0 &amp; 2
     * </pre>
     */
    boolean hasUuid();
    /**
     * <code>optional string uuid = 2;</code>
     *
     * <pre>
     * Required for types 0 &amp; 2
     * </pre>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 2;</code>
     *
     * <pre>
     * Required for types 0 &amp; 2
     * </pre>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional bytes data = 4;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 4;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>optional int32 contentLength = 5;</code>
     *
     * <pre>
     * Optional: Used for Integrity check, if protobuf does not fill this in automatically, then it should be discarded
     * </pre>
     */
    boolean hasContentLength();
    /**
     * <code>optional int32 contentLength = 5;</code>
     *
     * <pre>
     * Optional: Used for Integrity check, if protobuf does not fill this in automatically, then it should be discarded
     * </pre>
     */
    int getContentLength();
  }
  /**
   * Protobuf type {@code some.photo.package.PhotoRequest}
   */
  public static final class PhotoRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:some.photo.package.PhotoRequest)
      PhotoRequestOrBuilder {
    // Use PhotoRequest.newBuilder() to construct.
    private PhotoRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PhotoRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PhotoRequest defaultInstance;
    public static PhotoRequest getDefaultInstance() {
      return defaultInstance;
    }

    public PhotoRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PhotoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              some.package.275.SomeClass.PhotoRequest.RequestType value = some.package.275.SomeClass.PhotoRequest.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                requestType_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              uuid_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              name_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              contentLength_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return some.package.275.SomeClass.internal_static_some_photo_package_PhotoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return some.package.275.SomeClass.internal_static_some_photo_package_PhotoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              some.package.275.SomeClass.PhotoRequest.class, some.package.275.SomeClass.PhotoRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<PhotoRequest> PARSER =
        new com.google.protobuf.AbstractParser<PhotoRequest>() {
      public PhotoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhotoRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PhotoRequest> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code some.photo.package.PhotoRequest.RequestType}
     */
    public enum RequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>read = 0;</code>
       */
      read(0, 0),
      /**
       * <code>write = 1;</code>
       */
      write(1, 1),
      /**
       * <code>delete = 2;</code>
       */
      delete(2, 2),
      ;

      /**
       * <code>read = 0;</code>
       */
      public static final int read_VALUE = 0;
      /**
       * <code>write = 1;</code>
       */
      public static final int write_VALUE = 1;
      /**
       * <code>delete = 2;</code>
       */
      public static final int delete_VALUE = 2;


      public final int getNumber() { return value; }

      public static RequestType valueOf(int value) {
        switch (value) {
          case 0: return read;
          case 1: return write;
          case 2: return delete;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
              public RequestType findValueByNumber(int number) {
                return RequestType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return some.package.275.SomeClass.PhotoRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestType[] VALUES = values();

      public static RequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private RequestType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:some.photo.package.PhotoRequest.RequestType)
    }

    private int bitField0_;
    public static final int REQUESTTYPE_FIELD_NUMBER = 1;
    private some.package.275.SomeClass.PhotoRequest.RequestType requestType_;
    /**
     * <code>required .some.photo.package.PhotoRequest.RequestType requestType = 1 [default = read];</code>
     */
    public boolean hasRequestType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .some.photo.package.PhotoRequest.RequestType requestType = 1 [default = read];</code>
     */
    public some.package.275.SomeClass.PhotoRequest.RequestType getRequestType() {
      return requestType_;
    }

    public static final int UUID_FIELD_NUMBER = 2;
    private java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 2;</code>
     *
     * <pre>
     * Required for types 0 &amp; 2
     * </pre>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string uuid = 2;</code>
     *
     * <pre>
     * Required for types 0 &amp; 2
     * </pre>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 2;</code>
     *
     * <pre>
     * Required for types 0 &amp; 2
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 4;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes data = 4;</code>
     *
     * <pre>
     * Required for type 1
     * </pre>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int CONTENTLENGTH_FIELD_NUMBER = 5;
    private int contentLength_;
    /**
     * <code>optional int32 contentLength = 5;</code>
     *
     * <pre>
     * Optional: Used for Integrity check, if protobuf does not fill this in automatically, then it should be discarded
     * </pre>
     */
    public boolean hasContentLength() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 contentLength = 5;</code>
     *
     * <pre>
     * Optional: Used for Integrity check, if protobuf does not fill this in automatically, then it should be discarded
     * </pre>
     */
    public int getContentLength() {
      return contentLength_;
    }

    private void initFields() {
      requestType_ = some.package.275.SomeClass.PhotoRequest.RequestType.read;
      uuid_ = "";
      name_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      contentLength_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRequestType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, requestType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUuidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, contentLength_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, requestType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUuidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, contentLength_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static some.package.275.SomeClass.PhotoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static some.package.275.SomeClass.PhotoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static some.package.275.SomeClass.PhotoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static some.package.275.SomeClass.PhotoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static some.package.275.SomeClass.PhotoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static some.package.275.SomeClass.PhotoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static some.package.275.SomeClass.PhotoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static some.package.275.SomeClass.PhotoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static some.package.275.SomeClass.PhotoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static some.package.275.SomeClass.PhotoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(some.package.275.SomeClass.PhotoRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code some.photo.package.PhotoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:some.photo.package.PhotoRequest)
        some.package.275.SomeClass.PhotoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return some.package.275.SomeClass.internal_static_some_photo_package_PhotoRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return some.package.275.SomeClass.internal_static_some_photo_package_PhotoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                some.package.275.SomeClass.PhotoRequest.class, some.package.275.SomeClass.PhotoRequest.Builder.class);
      }

      // Construct using some.package.275.SomeClass.PhotoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        requestType_ = some.package.275.SomeClass.PhotoRequest.RequestType.read;
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        contentLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return some.package.275.SomeClass.internal_static_some_photo_package_PhotoRequest_descriptor;
      }

      public some.package.275.SomeClass.PhotoRequest getDefaultInstanceForType() {
        return some.package.275.SomeClass.PhotoRequest.getDefaultInstance();
      }

      public some.package.275.SomeClass.PhotoRequest build() {
        some.package.275.SomeClass.PhotoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public some.package.275.SomeClass.PhotoRequest buildPartial() {
        some.package.275.SomeClass.PhotoRequest result = new some.package.275.SomeClass.PhotoRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestType_ = requestType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.contentLength_ = contentLength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof some.package.275.SomeClass.PhotoRequest) {
          return mergeFrom((some.package.275.SomeClass.PhotoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(some.package.275.SomeClass.PhotoRequest other) {
        if (other == some.package.275.SomeClass.PhotoRequest.getDefaultInstance()) return this;
        if (other.hasRequestType()) {
          setRequestType(other.getRequestType());
        }
        if (other.hasUuid()) {
          bitField0_ |= 0x00000002;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasContentLength()) {
          setContentLength(other.getContentLength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequestType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        some.package.275.SomeClass.PhotoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (some.package.275.SomeClass.PhotoRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private some.package.275.SomeClass.PhotoRequest.RequestType requestType_ = some.package.275.SomeClass.PhotoRequest.RequestType.read;
      /**
       * <code>required .some.photo.package.PhotoRequest.RequestType requestType = 1 [default = read];</code>
       */
      public boolean hasRequestType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .some.photo.package.PhotoRequest.RequestType requestType = 1 [default = read];</code>
       */
      public some.package.275.SomeClass.PhotoRequest.RequestType getRequestType() {
        return requestType_;
      }
      /**
       * <code>required .some.photo.package.PhotoRequest.RequestType requestType = 1 [default = read];</code>
       */
      public Builder setRequestType(some.package.275.SomeClass.PhotoRequest.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .some.photo.package.PhotoRequest.RequestType requestType = 1 [default = read];</code>
       */
      public Builder clearRequestType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestType_ = some.package.275.SomeClass.PhotoRequest.RequestType.read;
        onChanged();
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 2;</code>
       *
       * <pre>
       * Required for types 0 &amp; 2
       * </pre>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string uuid = 2;</code>
       *
       * <pre>
       * Required for types 0 &amp; 2
       * </pre>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 2;</code>
       *
       * <pre>
       * Required for types 0 &amp; 2
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 2;</code>
       *
       * <pre>
       * Required for types 0 &amp; 2
       * </pre>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 2;</code>
       *
       * <pre>
       * Required for types 0 &amp; 2
       * </pre>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 2;</code>
       *
       * <pre>
       * Required for types 0 &amp; 2
       * </pre>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 4;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes data = 4;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 4;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 4;</code>
       *
       * <pre>
       * Required for type 1
       * </pre>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int contentLength_ ;
      /**
       * <code>optional int32 contentLength = 5;</code>
       *
       * <pre>
       * Optional: Used for Integrity check, if protobuf does not fill this in automatically, then it should be discarded
       * </pre>
       */
      public boolean hasContentLength() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 contentLength = 5;</code>
       *
       * <pre>
       * Optional: Used for Integrity check, if protobuf does not fill this in automatically, then it should be discarded
       * </pre>
       */
      public int getContentLength() {
        return contentLength_;
      }
      /**
       * <code>optional int32 contentLength = 5;</code>
       *
       * <pre>
       * Optional: Used for Integrity check, if protobuf does not fill this in automatically, then it should be discarded
       * </pre>
       */
      public Builder setContentLength(int value) {
        bitField0_ |= 0x00000010;
        contentLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 contentLength = 5;</code>
       *
       * <pre>
       * Optional: Used for Integrity check, if protobuf does not fill this in automatically, then it should be discarded
       * </pre>
       */
      public Builder clearContentLength() {
        bitField0_ = (bitField0_ & ~0x00000010);
        contentLength_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:some.photo.package.PhotoRequest)
    }

    static {
      defaultInstance = new PhotoRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:some.photo.package.PhotoRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_some_photo_package_PhotoResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_some_photo_package_PhotoResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_some_photo_package_PhotoRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_some_photo_package_PhotoRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Photo.proto\022\022some.photo.package\"\270\002\n\rPh" +
      "otoResponse\022M\n\014responseFlag\030\001 \002(\0162..some" +
      ".photo.package.PhotoResponse.ResponseFla" +
      "g:\007success\022J\n\014responseType\030\002 \002(\0162..some." +
      "photo.package.PhotoResponse.ResponseType" +
      ":\004read\022\024\n\014lastModified\030\003 \001(\003\022\014\n\004uuid\030\004 \001" +
      "(\t\022\r\n\005photo\030\005 \001(\014\"(\n\014ResponseFlag\022\013\n\007suc" +
      "cess\020\000\022\013\n\007failure\020\001\"/\n\014ResponseType\022\010\n\004r" +
      "ead\020\000\022\t\n\005write\020\001\022\n\n\006delete\020\002\"\310\001\n\014PhotoRe" +
      "quest\022G\n\013requestType\030\001 \002(\0162,.some.photo.",
      "package.PhotoRequest.RequestType:\004read\022\014" +
      "\n\004uuid\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\014\n\004data\030\004 \001(\014" +
      "\022\025\n\rcontentLength\030\005 \001(\005\".\n\013RequestType\022\010" +
      "\n\004read\020\000\022\t\n\005write\020\001\022\n\n\006delete\020\002B\035\n\020some." +
      "package.275B\tSomeClass"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_some_photo_package_PhotoResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_some_photo_package_PhotoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_some_photo_package_PhotoResponse_descriptor,
        new java.lang.String[] { "ResponseFlag", "ResponseType", "LastModified", "Uuid", "Photo", });
    internal_static_some_photo_package_PhotoRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_some_photo_package_PhotoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_some_photo_package_PhotoRequest_descriptor,
        new java.lang.String[] { "RequestType", "Uuid", "Name", "Data", "ContentLength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
